# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string

menu:
- {name: 'Research', folder: 'pages', file: 'research.html'}
- {name: 'CV', file: 'CV.pdf'}
#- {name: 'Contact', folder: 'pages', file: 'contact.html'}
social:
- {icon: 'envelope', link: 'mailto:huanan.shi@bcm.edu'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/fredhnshi/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?hl=en&user=xdfuE6sAAAAJ'}
- {icon: 'github', link: 'https://github.com/huananfshi/'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
